name: Individual Workflow

on:
 push:
  branches:
   - main


jobs:
 update_html_and_readme:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Repository
     uses: actions/Checkout@v3
      sed -i '/<\/body>/i <p>Updated by Team Leader on '"$(date)"'</p>' index.html
      sed -i '/<\/body>/i <p>Updated by tegan1 on '"$(date)"'</p>' index.html
      sed -i '/<\/body>/i <p>Updated by tegan2 on '"$(date)"'</p>' index.html
